### ISSUE TITLE
Delete Backend Error

### ISSUE THREAD

**Issue by dweinholz** [deNBI/cloud-portal-client#617]

**Comment by dweinholz** [comment]
2021-02-18 08:14:00,958 - VirtualMachineHandler - delete_backend  - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/code/VirtualMachineService/VirtualMachineHandler.py", line 1443, in delete_backend
    return str(response.json())
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dweinholz** [comment]
def delete_backend(self, id):
        delete_url = "{0}/backends/{1}".format(self.RE_BACKEND_URL, id)
        try:
            response = req.delete(
                delete_url,
                timeout=(30, 30),
                headers={"X-API-KEY": self.FORC_API_KEY},
                verify=True,
            )
            if response.status_code != 200:
                return str(response.json())  < --- fails
            elif response.status_code == 200:
                return str(True)
        except Timeout as e:
            LOG.info(msg="create_backend timed out. {0}".format(e))
            return str(-1)
        except Exception as e:
            LOG.exception(e)
            return str(-1)
